### ISSUE TITLE
Cannot include different versions of the framework 'FBLPromises.framework'

### ISSUE THREAD

**Issue by tromcap1102** [JimmyPun610/BarcodeScanner.Mobile#139]
I have this problem when using it with Plugin.FirebasePushNotification in Xamarin Form iOS Project. Please help me
![Ảnh chụp Màn hình 2022-09-10 lúc 14 26 49](https://user-images.githubusercontent.com/49108434/189473740-4abf575a-c553-449e-b1a9-45cc13fb8928.png)

**Comment by JimmyPun610** [comment]
When you look into the package Plugin.FirebasePushNotification, you can see the dependency is old version of firebase. I think this is the reason why you have this issue.
```
Xamarin.iOS 1.0

[Xamarin.Firebase.iOS.CloudMessaging](https://www.nuget.org/packages/Xamarin.Firebase.iOS.CloudMessaging/) (>= 4.3.0)
```

And Xamarin.Firebase.iOS.CloudMessaging 4.3.0 depends on

```
Xamarin.iOS 1.0

[Xamarin.Build.Download](https://www.nuget.org/packages/Xamarin.Build.Download/) (>= 0.10.0)
[Xamarin.Firebase.iOS.Core](https://www.nuget.org/packages/Xamarin.Firebase.iOS.Core/) (>= 6.6.6)
[Xamarin.Firebase.iOS.Installations](https://www.nuget.org/packages/Xamarin.Firebase.iOS.Installations/) (>= 1.1.1)
[Xamarin.Firebase.iOS.InstanceID](https://www.nuget.org/packages/Xamarin.Firebase.iOS.InstanceID/) (>= 4.3.3)
```


In BarcodeScanner, it is using the latest version.

```
[Xamarin.Firebase.iOS.Core](https://www.nuget.org/packages/Xamarin.Firebase.iOS.Core/) (>= 8.10.0.1)
```

So for the possible fix, I think you could try to update the cloud message library or use the old version of the barcode scanner...

Maybe be BarcodeScanner.XF 5.0.9 would work
https://www.nuget.org/packages/BarcodeScanner.XF/5.0.9

Otherwise, 4.8.1.1 should work as it is using the same version of Xamarin.Firebase.iOS.Core
https://www.nuget.org/packages/BarcodeScanner.XF/4.8.1.1

**Comment by tromcap1102** [comment]
Thanks, This problem solved with your method
