### ISSUE TITLE
Autofocus not working on iPhone 15

### ISSUE THREAD

**Issue by criistii** [JimmyPun610/BarcodeScanner.Mobile#202]
Sadly, I do not have a lot of information for the issue since I do not own an iPhone 15, and my iPhone 12 works just fine. The customer is complaining that autofocus is not working on the new iPhones. Any chance you have encountered this? Is there a fix?

**Comment by mos379** [comment]
gotta revisit #174

**Comment by LennardF1989** [comment]
Can confirm, but based on #174 can't really see why it's not working. @mos379 Did you had a chance to look at it already?

**Comment by jeffreysullivanjr** [comment]
From what I have found the issue is with the 3rd camera lens added in the iPhone 14 Pro and iPhone 15 Pro. The current method of accessing the camera through `AVCaptureDevice.DevicesWithMediaType()` always returns the `BuiltInWideAngleCamera` which isn't able to focus at close range in the iPhone 14 & 15 Pro. To support the Pro phone cameras you need to do something like the following: 

`AVCaptureDevice GetCamera(AVCaptureDevicePosition position)
        {
            if ((AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInTripleCamera, AVMediaTypes.Video, position)) != null)
            {
                return currentCameraDevice = AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInTripleCamera, AVMediaTypes.Video, position);
            }
            if ((AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInDualCamera, AVMediaTypes.Video, position)) != null)
            {
                return currentCameraDevice = AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInDualCamera, AVMediaTypes.Video, position);
            }

            return currentCameraDevice = AVCaptureDevice.DevicesWithMediaType(AVMediaType.Video).FirstOrDefault(d => d.Position == position);
        }`

which will walk the camera stack and return the correct camera. In my testing this works on the iPhone 15 Pro and on the iPhone 12 (non-Pro).

**Comment by LennardF1989** [comment]
Thank you for sharing @jeffreysullivanjr! I'll have access to an iPhone again on monday and can give this theory a test.
